In [24]:
import pandas as pd
import numpy as np
students=pd.read_csv("student_records_dirty.csv")
students.head()

,student_id,first_name,last_name,age,major,enrollment_date,course_grade,gpa,tuition_paid
0,17270,Taylor,Chen,23,Bio,2024-02-28,12,3.8,17548.10
1,10860,Olivia,Martinez,73,Computer Science,"January 30, 2024",12,2.7,13129.13
2,15390,Priya,Garcia,52,bio,2024-02-10,95,1.9,19051.36
3,15191,Priya,Anderson,61,CS,2024-02-08,3,2.0,17242.61
4,15734,Noah,Wilson,36,Comp Sci,"February 08, 2024",-20,3.2,NaN

In [3]:
students.shape

(355, 9)

In [4]:
students.sample(10)

,student_id,first_name,last_name,age,major,enrollment_date,course_grade,gpa,tuition_paid
183,15855,Ethan,Martinez,45,Comp Sci,"January 20, 2024",85,3.5,19377.47
69,11016,Sam,Johnson,85,CS,"March 10, 2024",52,1.9,15556.09
116,16910,Jordan,Martinez,50,Comp Sci,2024-02-14,12,NaN,17015.98
14,15311,Jamie,Johnson,41,Psychology,2024-03-12,ninety,1.9,16343.04
241,13108,Jamie,Brown,28,Computer Science,2024-05-31,NaN,NaN,15316.16
336,11409,Ravi,Kim,20,Computer Science,2024-02-28,ninety,NaN,20000.00
51,10775,Maria,WILSON,17,PSYCH,2024-01-28,0,NaN,20000.00
300,17339,Emma,Brown,20,Psych,"May 21, 2024",ninety,1.9,13454.40
136,16892,ZOE,Johnson,29,computer science,"April 30, 2024",12,2.0,15995.53
201,17777,Jamie,Anderson,83,Biology,2024-03-10,-20,1.9,NaN

In [5]:
students['course_grade'].value_counts()

course_grade
100         36
12          34
 ninety     32
95          27
0           27
-20         27
 85         25
52          25
64          25
88          24
3           22
76          19
Name: count, dtype: int64

In [6]:
students['major'].value_counts()

major
Bio                 38
Comp Sci            38
Biology             38
PSYCH               33
CS                  31
psych               30
Psychology          30
Computer Science    29
BIO                 27
Psych               24
computer science    21
bio                 16
Name: count, dtype: int64

In [25]:
students.drop_duplicates()

,student_id,first_name,last_name,age,major,enrollment_date,course_grade,gpa,tuition_paid
0,17270,Taylor,Chen,23,Bio,2024-02-28,12,3.8,17548.10
1,10860,Olivia,Martinez,73,Computer Science,"January 30, 2024",12,2.7,13129.13
2,15390,Priya,Garcia,52,bio,2024-02-10,95,1.9,19051.36
3,15191,Priya,Anderson,61,CS,2024-02-08,3,2.0,17242.61
4,15734,Noah,Wilson,36,Comp Sci,"February 08, 2024",-20,3.2,NaN
...,...,...,...,...,...,...,...,...,...
345,10537,Taylor,Martinez,82,Biology,2024-02-18,-20,3.8,20783.40
346,15986,Sam,Davis,59,Computer Science,2024-03-19,64,2.0,18087.82
347,11841,Evan,Martinez,39,PSYCH,"March 28, 2024",95,2.7,20000.00
348,18716,Aisha,Brown,71,Psychology,"January 01, 2024",ninety,NaN,13621.58
349,16971,Ben,Martinez,32,Comp Sci,"April 30, 2024",3,3.8,14181.07

In [35]:
students['major']=students['major'].str.strip().str.capitalize()
students

,student_id,first_name,last_name,age,major,enrollment_date,course_grade,gpa,tuition_paid
0,17270,Taylor,Chen,23,Biology,2024-02-28,12,3.8,17548.10
1,10860,Olivia,Martinez,73,Computer science,"January 30, 2024",12,2.7,13129.13
2,15390,Priya,Garcia,52,Biology,2024-02-10,95,1.9,19051.36
3,15191,Priya,Anderson,61,Computer science,2024-02-08,3,2.0,17242.61
4,15734,Noah,Wilson,36,Computer science,"February 08, 2024",-20,3.2,NaN
...,...,...,...,...,...,...,...,...,...
350,14931,Mia,Davis,52,Psychology,2024-02-15,3,NaN,15961.60
351,18445,Jordan,Anderson,79,Biology,2024-03-05,95,3.8,16868.60
352,13763,Luis,Smith,34,Computer science,"April 06, 2024",ninety,2.0,20000.00
353,17629,Ethan,Smith,73,Psychology,2024-02-18,85,3.2,24309.50
354,17777,Jamie,Anderson,83,Biology,2024-03-10,-20,1.9,NaN

In [33]:
students['major']=students['major'].replace({
"Comp sci": "Computer Science",
"Cs" : "Computer Science",
"Computer science": "Computer Science",
"Bio": "Biology",
"bio": "Biology",
"Psych": "Psychology"
})
students['major'].value_counts()

major
Biology             119
Computer Science    119
Psychology          117
Name: count, dtype: int64

In [36]:
students['course_grade'].value_counts()

course_grade
100         36
12          34
 ninety     32
95          27
0           27
-20         27
 85         25
52          25
64          25
88          24
3           22
76          19
Name: count, dtype: int64

In [39]:
students["course_grade"]=students["course_grade"].str.strip()
students.loc[students["course_grade"]=="ninety","course_grade"]=90
students['course_grade'].value_counts()

course_grade
100    36
12     34
90     32
95     27
0      27
-20    27
85     25
52     25
64     25
88     24
3      22
76     19
Name: count, dtype: int64

In [ ]:
students["age"].describe()

count    355.000000
mean      53.915493
std       26.866981
min      -12.000000
25%       33.000000
50%       52.000000
75%       72.500000
max      230.000000
Name: age, dtype: float64

In [ ]:
students.loc[students["age"]<5,"age"] = np.nan
students.loc[students["age"]>120,"age"] = np.nan

In [46]:
students["full_name"]=students["first_name"] + ' ' + students["last_name"]

In [51]:
students["age_group"] = pd.cut(
    students["age"],
    bins=[0,25,65,120], 
    labels=["Young Adults", "Working Adults", "Retired"]
    )
students["age_group"].value_counts()

age_group
Working Adults    187
Retired           122
Young Adults       41
Name: count, dtype: int64

In [52]:
students['cost_per_semester'] = students['tuition_paid']/3

In [ ]:
students['enrollment_date']
# wow dates are really messed up!!!

0                 2024-02-28
1           January 30, 2024
2                 2024-02-10
3                 2024-02-08
4          February 08, 2024
                 ...
352           April 06, 2024
353               2024-02-18
354               2024-03-10
 ninety                  NaN
ninety                   NaN
Name: enrollment_date, Length: 357, dtype: object

In [60]:
#students['enrollment_date']=pd.to_datetime(students["enrollment_date"])

students['enrollment_date'] = pd.to_datetime(students['enrollment_date'],format = 'mixed',
dayfirst = False)
students["enrollment_date"]

0         2024-02-28
1         2024-01-30
2         2024-02-10
3         2024-02-08
4         2024-02-08
             ...
352       2024-04-06
353       2024-02-18
354       2024-03-10
 ninety          NaT
ninety           NaT
Name: enrollment_date, Length: 357, dtype: datetime64[ns]